const String COMPANY = "company";
const String WORK = "work";
const String ALARM= "alarm";
const String EXPENSE = "expense";
const String USER = "user";
const String NOTICE = "notice";
const String TEAM = "team";
const String POSITION = "position";
const String COMMENT = "comment";
const String COMMENTS = "comments";
const String APPROVAL = "approval";
const String ATTENDANCE = "attendance";
const String APP_NAME = "MY COMPANY";
const String APP_VERSION = "1.0.1";
const String GRADE = "grade";
const String WORKAPPROVAL = "workApproval";
const String WIFI = "wifi";
const String QNA = "QnA";

